[character]
success_symbol = "[≫](green)"
error_symbol = "[≫](red)"
vimcmd_symbol = "[≪](green)"
vimcmd_replace_one_symbol = "[≪](purple)"
vimcmd_replace_symbol = "[≪](purple)"
vimcmd_visual_symbol = "[≪](yellow)"

[directory]
format = "[☼](yellow) [$path]($style)[$read_only]($read_only_style) "
read_only = " "